### ISSUE TITLE
این مخزن چیست؟

### ISSUE THREAD

**Issue by ekm507** [DearRude/test-repo#1]
یه مسئله‌ای هست و اون اینه که این مخزن هیچ توضیحی دربارهٔ این که چی هست نمی‌ده.
آزمایش؟ آزمایش چی؟
نکنه این یه روش خلاقانه برای کنترل یه چیزیه؟
واقعاً نمی‌تونم فرض کنم که این هیچی نیست :))
خودت بگو این چیه؟ :)

**Comment by DearRude** [comment]
واسه [اینجا](https://t.me/cs_fum/187)ست. به زودی حذفش خواهم کرد.
